#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def run_once(binary: Path, build_dir: Path, artifact: Path, out_copy: Path) -> str:
    if artifact.exists():
        artifact.unlink()
    subprocess.run([str(binary)], cwd=build_dir, check=True)
    if not artifact.exists():
        raise RuntimeError(f"expected artifact was not created: {artifact}")
    shutil.copy2(artifact, out_copy)
    return sha256_file(artifact)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Run VM workload signature test twice and require bit-identical artifact hashes."
    )
    p.add_argument("--build-dir", default="build", help="CMake build directory")
    p.add_argument(
        "--binary",
        default="t81_vm_workload_determinism_tiers_test",
        help="Test binary name inside build directory",
    )
    p.add_argument(
        "--artifact-relpath",
        default="artifacts/vm_workload_determinism_signatures.log",
        help="Relative path (from build dir) of the deterministic artifact generated by the test binary",
    )
    p.add_argument(
        "--out-json",
        default="artifacts/ci_reports/vm_repeatability_report.json",
        help="Output JSON report path",
    )
    args = p.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    build_dir = (repo_root / args.build_dir).resolve()
    binary = build_dir / args.binary
    artifact = build_dir / args.artifact_relpath
    out_json = (repo_root / args.out_json).resolve()

    if sys.platform == "win32" and not binary.exists():
        binary = binary.with_suffix(".exe")
    if not binary.exists():
        raise FileNotFoundError(f"missing test binary: {binary}")

    run1_copy = artifact.with_suffix(".run1.log")
    run2_copy = artifact.with_suffix(".run2.log")

    hash1 = run_once(binary, build_dir, artifact, run1_copy)
    hash2 = run_once(binary, build_dir, artifact, run2_copy)

    ok = hash1 == hash2
    report = {
        "schema": "t81.vm.repeatability.v1",
        "binary": str(binary),
        "artifact": str(artifact),
        "run1_sha256": hash1,
        "run2_sha256": hash2,
        "bit_identical": ok,
    }
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(f"run1 sha256: {hash1}")
    print(f"run2 sha256: {hash2}")
    print(f"bit-identical: {'yes' if ok else 'no'}")
    print(f"artifact: {out_json}")
    if not ok:
        print("repeatability check failed: hashes differ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
