# CMake generated Testfile for 
# Source directory: /Users/t81dev/t81-foundation
# Build directory: /Users/t81dev/t81-foundation/build-make
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(t81_bigint_test "/Users/t81dev/t81-foundation/build-make/t81_bigint_test")
set_tests_properties(t81_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_fraction_test "/Users/t81dev/t81-foundation/build-make/t81_fraction_test")
set_tests_properties(t81_fraction_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_transpose_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_transpose_test")
set_tests_properties(t81_tensor_transpose_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_slice_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_slice_test")
set_tests_properties(t81_tensor_slice_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_reshape_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_reshape_test")
set_tests_properties(t81_tensor_reshape_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_loader_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_loader_test")
set_tests_properties(t81_tensor_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_canonfs_io_test "/Users/t81dev/t81-foundation/build-make/t81_canonfs_io_test")
set_tests_properties(t81_canonfs_io_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_ir_encoding_test "/Users/t81dev/t81-foundation/build-make/t81_ir_encoding_test")
set_tests_properties(t81_ir_encoding_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_hash_stub_test "/Users/t81dev/t81-foundation/build-make/t81_hash_stub_test")
set_tests_properties(t81_hash_stub_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_axion_stub_test "/Users/t81dev/t81-foundation/build-make/t81_axion_stub_test")
set_tests_properties(t81_axion_stub_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_codec_base243_test "/Users/t81dev/t81-foundation/build-make/t81_codec_base243_test")
set_tests_properties(t81_codec_base243_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_codec_base81_test "/Users/t81dev/t81-foundation/build-make/t81_codec_base81_test")
set_tests_properties(t81_codec_base81_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_shape_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_shape_test")
set_tests_properties(t81_tensor_shape_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_ternary_arith_test "/Users/t81dev/t81-foundation/build-make/t81_ternary_arith_test")
set_tests_properties(t81_ternary_arith_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_matmul_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_matmul_test")
set_tests_properties(t81_tensor_matmul_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_reduce_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_reduce_test")
set_tests_properties(t81_tensor_reduce_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_broadcast_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_broadcast_test")
set_tests_properties(t81_tensor_broadcast_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_entropy_test "/Users/t81dev/t81-foundation/build-make/t81_entropy_test")
set_tests_properties(t81_entropy_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_elementwise_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_elementwise_test")
set_tests_properties(t81_tensor_elementwise_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_c_api_bigint_test "/Users/t81dev/t81-foundation/build-make/t81_c_api_bigint_test")
set_tests_properties(t81_c_api_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_tensor_unary_test "/Users/t81dev/t81-foundation/build-make/t81_tensor_unary_test")
set_tests_properties(t81_tensor_unary_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_hanoi_integration_test "/Users/t81dev/t81-foundation/build-make/t81_hanoi_integration_test")
set_tests_properties(t81_hanoi_integration_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_lang_vm_test "/Users/t81dev/t81-foundation/build-make/t81_lang_vm_test")
set_tests_properties(t81_lang_vm_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_vm_load_store_test "/Users/t81dev/t81-foundation/build-make/t81_vm_load_store_test")
set_tests_properties(t81_vm_load_store_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_vm_divmod_test "/Users/t81dev/t81-foundation/build-make/t81_vm_divmod_test")
set_tests_properties(t81_vm_divmod_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_vm_illegal_test "/Users/t81dev/t81-foundation/build-make/t81_vm_illegal_test")
set_tests_properties(t81_vm_illegal_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_vm_bounds_test "/Users/t81dev/t81-foundation/build-make/t81_vm_bounds_test")
set_tests_properties(t81_vm_bounds_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_canonfs_driver_test "/Users/t81dev/t81-foundation/build-make/t81_canonfs_driver_test")
set_tests_properties(t81_canonfs_driver_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_vm_trace_test "/Users/t81dev/t81-foundation/build-make/t81_vm_trace_test")
set_tests_properties(t81_vm_trace_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_vm_jump_flags_test "/Users/t81dev/t81-foundation/build-make/t81_vm_jump_flags_test")
set_tests_properties(t81_vm_jump_flags_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_lang_parser_vm_test "/Users/t81dev/t81-foundation/build-make/t81_lang_parser_vm_test")
set_tests_properties(t81_lang_parser_vm_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
add_test(t81_lang_typecheck_test "/Users/t81dev/t81-foundation/build-make/t81_lang_typecheck_test")
set_tests_properties(t81_lang_typecheck_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/t81dev/t81-foundation/CMakeLists.txt;195;add_test;/Users/t81dev/t81-foundation/CMakeLists.txt;0;")
