// experimental/ternaryos/hal/qemu_armv8_efi_stub.c
//
// Freestanding AArch64 UEFI entry point for the QEMU AArch64 + EDK2
// developer lane (Slice 6).  This file is compiled without a C runtime
// (-ffreestanding -nostdlib) and linked with lld-link to produce
// EFI/BOOT/BOOTAA64.EFI for the QEMU virt machine.
//
// At runtime it:
//   1. Emits a serial banner via EFI ConOut so the probe script can detect
//      execution in the serial log.
//   2. Opens the FAT32 boot volume and writes two artefacts under \TERNOS\:
//        efi-slice6-ran.txt  — execution marker
//        slice6-boot-report.txt — Slice 4+5 readiness report (generated by
//            qemu_slice6_startup_snapshot at build time and embedded as
//            kGeneratedQemuSlice6Startup in qemu_slice6_startup.h).
//   3. Calls ternaryos_hal_main_c() — provided by virtualbox_armv8_efi_shim.c
//      which is a thin hosted stub that validates the boot context and
//      returns 0.
//   4. Writes the boot-report and returns EFI_SUCCESS on success.
//
// References: RFC-00B0 §4.4 (ethics-first boot), RFC-00B3 §3.9 (QEMU lane),
//             RFC-00B6 §5.2 (SVC trap), RFC-00B1 §3.1 (kernel/user split).

#include "hal_c_abi.h"

// ── Slice 6 report header — generated at build time by
//    t81_ternaryos_qemu_slice6_snapshot ────────────────────────────────────
#include "qemu_slice6_startup.h"

#include <stdint.h>

#ifndef EFIAPI
#define EFIAPI
#endif

typedef void* EFI_HANDLE;
typedef uint64_t EFI_STATUS;
typedef unsigned long long UINTN;
typedef unsigned short CHAR16;
typedef struct EFI_SYSTEM_TABLE EFI_SYSTEM_TABLE;
typedef struct EFI_BOOT_SERVICES EFI_BOOT_SERVICES;
typedef struct EFI_FILE_PROTOCOL EFI_FILE_PROTOCOL;
typedef struct EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL;

typedef struct {
  uint32_t Data1;
  uint16_t Data2;
  uint16_t Data3;
  uint8_t  Data4[8];
} EFI_GUID;

// Minimal EFI_MEMORY_DESCRIPTOR — only the MapKey from GetMemoryMap is used;
// the descriptor contents are intentionally ignored.
typedef struct {
  uint32_t Type;
  uint32_t Pad;
  uint64_t PhysicalStart;
  uint64_t VirtualStart;
  uint64_t NumberOfPages;
  uint64_t Attribute;
} EFI_MEMORY_DESCRIPTOR;

typedef struct {
  uint64_t Signature;
  uint32_t Revision;
  uint32_t HeaderSize;
  uint32_t CRC32;
  uint32_t Reserved;
} EFI_TABLE_HEADER;

typedef struct {
  uint32_t Revision;
  EFI_HANDLE ParentHandle;
  EFI_SYSTEM_TABLE* SystemTable;
  EFI_HANDLE DeviceHandle;
  void* FilePath;
  void* Reserved;
  uint32_t LoadOptionsSize;
  void* LoadOptions;
  void* ImageBase;
  uint64_t ImageSize;
  uint32_t ImageCodeType;
  uint32_t ImageDataType;
  void* Unload;
} EFI_LOADED_IMAGE_PROTOCOL;

typedef struct {
  uint64_t Revision;
  EFI_STATUS(EFIAPI* OpenVolume)(void* self, EFI_FILE_PROTOCOL** root);
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

struct EFI_FILE_PROTOCOL {
  uint64_t Revision;
  EFI_STATUS(EFIAPI* Open)(EFI_FILE_PROTOCOL* self,
                           EFI_FILE_PROTOCOL** new_handle,
                           CHAR16* file_name,
                           uint64_t open_mode,
                           uint64_t attributes);
  EFI_STATUS(EFIAPI* Close)(EFI_FILE_PROTOCOL* self);
  void* Delete;
  void* Read;
  EFI_STATUS(EFIAPI* Write)(EFI_FILE_PROTOCOL* self, UINTN* buffer_size, void* buffer);
  void* GetPosition;
  void* SetPosition;
  void* GetInfo;
  void* SetInfo;
  void* Flush;
  void* OpenEx;
  void* ReadEx;
  void* WriteEx;
  void* FlushEx;
};

struct EFI_BOOT_SERVICES {
  EFI_TABLE_HEADER Hdr;                        // offset   0 (24 bytes)
  void* RaiseTPL;                              // offset  24
  void* RestoreTPL;                            // offset  32
  void* AllocatePages;                         // offset  40
  void* FreePages;                             // offset  48
  // GetMemoryMap — typed so we can retrieve the MapKey for ExitBootServices.
  EFI_STATUS(EFIAPI* GetMemoryMap)(            // offset  56
      UINTN* MemoryMapSize,
      EFI_MEMORY_DESCRIPTOR* MemoryMap,
      UINTN* MapKey,
      UINTN* DescriptorSize,
      uint32_t* DescriptorVersion);
  void* AllocatePool;                          // offset  64
  void* FreePool;                              // offset  72
  void* CreateEvent;                           // offset  80
  void* SetTimer;                              // offset  88
  void* WaitForEvent;                          // offset  96
  void* SignalEvent;                           // offset 104
  void* CloseEvent;                            // offset 112
  void* CheckEvent;                            // offset 120
  void* InstallProtocolInterface;              // offset 128
  void* ReinstallProtocolInterface;            // offset 136
  void* UninstallProtocolInterface;            // offset 144
  EFI_STATUS(EFIAPI* HandleProtocol)(          // offset 152
      EFI_HANDLE handle, EFI_GUID* protocol, void** interface);
  void* Reserved;                              // offset 160
  void* RegisterProtocolNotify;                // offset 168
  void* LocateHandle;                          // offset 176
  void* LocateDevicePath;                      // offset 184
  void* InstallConfigurationTable;             // offset 192
  void* LoadImage;                             // offset 200
  void* StartImage;                            // offset 208
  void* Exit;                                  // offset 216
  void* UnloadImage;                           // offset 224
  EFI_STATUS(EFIAPI* ExitBootServices)(        // offset 232
      EFI_HANDLE ImageHandle,
      UINTN MapKey);
};

struct EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL {
  void* Reset;
  EFI_STATUS(EFIAPI* OutputString)(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL* self, CHAR16* string);
};

struct EFI_SYSTEM_TABLE {
  EFI_TABLE_HEADER Hdr;
  CHAR16* FirmwareVendor;
  uint32_t FirmwareRevision;
  EFI_HANDLE ConsoleInHandle;
  void* ConIn;
  EFI_HANDLE ConsoleOutHandle;
  void* ConOut;
  EFI_HANDLE StandardErrorHandle;
  void* StdErr;
  void* RuntimeServices;
  EFI_BOOT_SERVICES* BootServices;
  UINTN NumberOfTableEntries;
  void* ConfigurationTable;
};

#define EFI_SUCCESS 0
#define EFI_LOAD_ERROR 1
#define EFI_WRITE_PROTECTED 8
#define EFI_OPEN_MODE_READ   0x0000000000000001ULL
#define EFI_OPEN_MODE_WRITE  0x0000000000000002ULL
#define EFI_OPEN_MODE_CREATE 0x8000000000000000ULL

// ── GUID constants ────────────────────────────────────────────────────────
static const EFI_GUID kEfiLoadedImageProtocolGuid = {
    0x5B1B31A1, 0x9562, 0x11D2,
    {0x8E, 0x3F, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B}};
static const EFI_GUID kEfiSimpleFileSystemProtocolGuid = {
    0x964E5B22, 0x6459, 0x11D2,
    {0x8E, 0x39, 0x00, 0xA0, 0xC9, 0x69, 0x72, 0x3B}};

// ── Path and content constants ────────────────────────────────────────────
static const CHAR16 kMarkerPath[]  = L"\\TERNOS\\efi-slice6-ran.txt";
static const CHAR16 kReportPath[]  = L"\\TERNOS\\slice6-boot-report.txt";
static const char   kMarkerText[]  = "TERNOS_QEMU_SLICE6_EFI_EXECUTED\n";
static const char   kBootBanner[]  = "Axion QEMU AArch64 EDK2 slice6\r\n";

// ── QEMU virt AArch64 memory map ─────────────────────────────────────────
static const TernaryOsMemoryRegion kQemuVirtMemoryMap[] = {
    {
        .base_phys  = 0x0000000040000000ULL,  // QEMU virt RAM base
        .size_bytes = 128ULL * 1024ULL * 1024ULL,
        .writable   = true,
        .executable = false,
    },
    {
        .base_phys  = 0x0000000048000000ULL,  // kernel load region
        .size_bytes = 4ULL * 1024ULL * 1024ULL,
        .writable   = true,
        .executable = true,
    },
};

static const char kPlatformId[] = "qemu-armv8:AArch64/EDK2/slice6-boot-probe";

// ── Minimal helpers ───────────────────────────────────────────────────────

static unsigned long ascii_length(const char* text) {
  unsigned long n = 0;
  while (text[n] != 0) ++n;
  return n;
}

static void ascii_to_char16(CHAR16* dest, unsigned long capacity,
                             const char* text) {
  unsigned long i = 0;
  if (capacity == 0) return;
  while (i + 1 < capacity && text[i] != 0) {
    dest[i] = (CHAR16)((unsigned char)text[i]);
    ++i;
  }
  dest[i] = 0;
}

// ── EFI console banner ────────────────────────────────────────────────────

static void emit_boot_banner(EFI_SYSTEM_TABLE* st) {
  CHAR16 banner[64];
  if (!st || !st->ConOut) return;
  EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL* con =
      (EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL*)st->ConOut;
  if (!con->OutputString) return;
  ascii_to_char16(banner, sizeof(banner) / sizeof(banner[0]), kBootBanner);
  con->OutputString(con, banner);
}

// ── Volume / file helpers ─────────────────────────────────────────────────

static EFI_STATUS open_root_volume(EFI_HANDLE image_handle,
                                   EFI_SYSTEM_TABLE* st,
                                   EFI_FILE_PROTOCOL** root_out) {
  if (!st || !st->BootServices || !st->BootServices->HandleProtocol)
    return EFI_LOAD_ERROR;

  EFI_LOADED_IMAGE_PROTOCOL* img = 0;
  EFI_STATUS s = st->BootServices->HandleProtocol(
      image_handle, (EFI_GUID*)&kEfiLoadedImageProtocolGuid, (void**)&img);
  if (s != EFI_SUCCESS || !img || !img->DeviceHandle) return EFI_LOAD_ERROR;

  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL* fs = 0;
  s = st->BootServices->HandleProtocol(
      img->DeviceHandle, (EFI_GUID*)&kEfiSimpleFileSystemProtocolGuid,
      (void**)&fs);
  if (s != EFI_SUCCESS || !fs || !fs->OpenVolume) return EFI_LOAD_ERROR;

  EFI_FILE_PROTOCOL* root = 0;
  s = fs->OpenVolume(fs, &root);
  if (s != EFI_SUCCESS || !root || !root->Open || !root->Close)
    return EFI_LOAD_ERROR;

  *root_out = root;
  return EFI_SUCCESS;
}

static EFI_STATUS write_root_file(EFI_FILE_PROTOCOL* root,
                                  const CHAR16* path,
                                  const char* text,
                                  unsigned long text_len) {
  if (!root || !root->Open || !root->Close) return EFI_LOAD_ERROR;
  EFI_FILE_PROTOCOL* file = 0;
  EFI_STATUS s = root->Open(root, &file, (CHAR16*)path,
                             EFI_OPEN_MODE_READ | EFI_OPEN_MODE_WRITE |
                                 EFI_OPEN_MODE_CREATE,
                             0);
  if (s != EFI_SUCCESS || !file || !file->Write || !file->Close)
    return EFI_WRITE_PROTECTED;
  UINTN bytes = text_len;
  s = file->Write(file, &bytes, (void*)text);
  file->Close(file);
  return s;
}

// ── Forward declaration of the post-ExitBootServices bare-metal entry ────────
// Implemented in qemu_slice6_bare_kernel.c; linked into the same PE/COFF EFI.
void qemu_bare_kernel_entry(void);

// ── Memory-map scratch buffer ─────────────────────────────────────────────────
// Used only to obtain the MapKey required by ExitBootServices.  The descriptor
// contents are never inspected; 32 KiB is ample for a 512 MiB QEMU VM.
#define MMAP_BUF_SIZE (32u * 1024u)
static uint8_t s_mmap_buf[MMAP_BUF_SIZE];

// ── EFI entry point ───────────────────────────────────────────────────────────

EFI_STATUS EFIAPI efi_main(EFI_HANDLE image_handle, EFI_SYSTEM_TABLE* st) {
  emit_boot_banner(st);

  // Open the FAT32 boot volume.
  EFI_FILE_PROTOCOL* root = 0;
  EFI_STATUS s = open_root_volume(image_handle, st, &root);
  if (s != EFI_SUCCESS) return s;

  // Write execution marker.
  s = write_root_file(root, kMarkerPath, kMarkerText,
                      ascii_length(kMarkerText));
  if (s != EFI_SUCCESS) {
    root->Close(root);
    return s;
  }

  // Write the Slice 6 boot report (generated by qemu_slice6_startup_snapshot).
  s = write_root_file(root, kReportPath, kGeneratedQemuSlice6Startup,
                      ascii_length(kGeneratedQemuSlice6Startup));
  root->Close(root);
  if (s != EFI_SUCCESS) return s;

  // ── Transition to bare-metal: terminate EFI boot services ────────────────
  //
  // GetMemoryMap returns the current map and, crucially, the MapKey that
  // ExitBootServices requires.  The firmware may change the map between calls,
  // so retry once with an updated size if the first attempt returns BUFFER_TOO_SMALL.

  EFI_BOOT_SERVICES* bs = st ? st->BootServices : 0;
  if (bs && bs->GetMemoryMap && bs->ExitBootServices) {
    UINTN mmap_size = MMAP_BUF_SIZE;
    UINTN map_key   = 0;
    UINTN desc_size = 0;
    uint32_t desc_ver = 0;

    s = bs->GetMemoryMap(&mmap_size,
                         (EFI_MEMORY_DESCRIPTOR*)(void*)s_mmap_buf,
                         &map_key, &desc_size, &desc_ver);
    // EFI_BUFFER_TOO_SMALL = 5; retry with firmware-provided size + slack.
    if (s == 5u) {
      mmap_size += 2u * desc_size;   // add two descriptor slots of slack
      if (mmap_size > MMAP_BUF_SIZE) mmap_size = MMAP_BUF_SIZE;
      s = bs->GetMemoryMap(&mmap_size,
                           (EFI_MEMORY_DESCRIPTOR*)(void*)s_mmap_buf,
                           &map_key, &desc_size, &desc_ver);
    }

    if (s == EFI_SUCCESS) {
      // ExitBootServices invalidates the EFI system table pointer.
      // After this call, st, bs, and all EFI services are gone.
      s = bs->ExitBootServices(image_handle, map_key);
      if (s == EFI_SUCCESS) {
        // ── Bare-metal execution from here ──────────────────────────────────
        // No C runtime, no EFI, no stack protector.  Only MMIO and CPU regs.
        qemu_bare_kernel_entry();
        // qemu_bare_kernel_entry() never returns on AArch64 bare-metal.
        // On hosted builds it returns immediately for testability.
        while (1) {}
      }
    }
  }

  // Fallback: ExitBootServices unavailable or failed — run the hosted shim.
  TernaryOsBootContext ctx;
  ctx.memory_map       = kQemuVirtMemoryMap;
  ctx.memory_map_len   =
      sizeof(kQemuVirtMemoryMap) / sizeof(kQemuVirtMemoryMap[0]);
  ctx.kernel_load_address = 0x0000000048000000ULL;
  ctx.stack_top           = 0x0000000047FFF000ULL;
  ctx.ethics_boot_required = true;
  ctx.platform_id          = kPlatformId;

  const int hal_result = ternaryos_hal_main_c(&ctx);
  return hal_result == 0 ? EFI_SUCCESS : EFI_LOAD_ERROR;
}
