include_guard(GLOBAL)

if(NOT MSVC)
  set(T81_SANITIZER_FLAGS "")
  if(T81_ENABLE_ASAN)
    list(APPEND T81_SANITIZER_FLAGS -fsanitize=address -fno-omit-frame-pointer)
    add_compile_definitions(T81_ASAN_ENABLED)
  endif()
  if(T81_ENABLE_UBSAN)
    list(APPEND T81_SANITIZER_FLAGS -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer)
  endif()
  if(T81_SANITIZER_FLAGS)
    add_compile_options(${T81_SANITIZER_FLAGS})
    add_link_options(${T81_SANITIZER_FLAGS})
    message(STATUS "Enabled sanitizers: ${T81_SANITIZER_FLAGS}")
  endif()
endif()
